// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/bus/bus.go

// Package bus is a generated GoMock package.
package bus

import (
	model "flip/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Channel mocks base method.
func (m *MockRepository) Channel() <-chan model.Event {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Channel")
	ret0, _ := ret[0].(<-chan model.Event)
	return ret0
}

// Channel indicates an expected call of Channel.
func (mr *MockRepositoryMockRecorder) Channel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Channel", reflect.TypeOf((*MockRepository)(nil).Channel))
}

// Publish mocks base method.
func (m *MockRepository) Publish(uploadID string, tx model.Transaction) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", uploadID, tx)
}

// Publish indicates an expected call of Publish.
func (mr *MockRepositoryMockRecorder) Publish(uploadID, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockRepository)(nil).Publish), uploadID, tx)
}
