// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/storage/storage.go

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	model "flip/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddFailed mocks base method.
func (m *MockRepository) AddFailed(ctx context.Context, id string, tx model.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFailed", ctx, id, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFailed indicates an expected call of AddFailed.
func (mr *MockRepositoryMockRecorder) AddFailed(ctx, id, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFailed", reflect.TypeOf((*MockRepository)(nil).AddFailed), ctx, id, tx)
}

// AddSuccess mocks base method.
func (m *MockRepository) AddSuccess(ctx context.Context, id string, tx model.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSuccess", ctx, id, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSuccess indicates an expected call of AddSuccess.
func (mr *MockRepositoryMockRecorder) AddSuccess(ctx, id, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSuccess", reflect.TypeOf((*MockRepository)(nil).AddSuccess), ctx, id, tx)
}

// Balance mocks base method.
func (m *MockRepository) Balance(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Balance", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Balance indicates an expected call of Balance.
func (mr *MockRepositoryMockRecorder) Balance(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Balance", reflect.TypeOf((*MockRepository)(nil).Balance), ctx, id)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Create", ctx, id)
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, id)
}

// Finish mocks base method.
func (m *MockRepository) Finish(ctx context.Context, id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Finish", ctx, id)
}

// Finish indicates an expected call of Finish.
func (mr *MockRepositoryMockRecorder) Finish(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finish", reflect.TypeOf((*MockRepository)(nil).Finish), ctx, id)
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, id string) (*model.Statement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.Statement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, id)
}

// IssuesFiltered mocks base method.
func (m *MockRepository) IssuesFiltered(ctx context.Context, id string, statuses []string, offset, limit int) ([]model.Transaction, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssuesFiltered", ctx, id, statuses, offset, limit)
	ret0, _ := ret[0].([]model.Transaction)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IssuesFiltered indicates an expected call of IssuesFiltered.
func (mr *MockRepositoryMockRecorder) IssuesFiltered(ctx, id, statuses, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssuesFiltered", reflect.TypeOf((*MockRepository)(nil).IssuesFiltered), ctx, id, statuses, offset, limit)
}

// Progress mocks base method.
func (m *MockRepository) Progress(ctx context.Context, id string) (*model.Statement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Progress", ctx, id)
	ret0, _ := ret[0].(*model.Statement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Progress indicates an expected call of Progress.
func (mr *MockRepositoryMockRecorder) Progress(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Progress", reflect.TypeOf((*MockRepository)(nil).Progress), ctx, id)
}
